export const PROFESSIONAL_VALUES: string[] = [
	'Achievement',
	'Action',
	'Balance',
	'Bravery',
	'Commitment',
	'Communication',
	'Community',
	'Compassion',
	'Confidence',
	'Conscientious',
	'Control',
	'Creativity',
	'Emotion',
	'Enthusiasm',
	'Equality',
	'Fairness',
	'Faith',
	'Family',
	'Fitness',
	'Flexibility',
	'Freedom',
	'Friendship',
	'Fun',
	'Grace',
	'Growth',
	'Happiness',
	'Harmony',
	'Honesty',
	'Hope',
	'Humanity',
	'Humility',
	'Inspiration',
	'Integrity',
	'Intelligence',
	'Joy',
	'Leadership',
	'Loyalty',
	'Passion',
	'Possibility',
	'Power',
	'Quality',
	'Reason',
	'Recognition',
	'Respect',
	'Responsibility',
	'Security',
	'Spirituality',
	'Transparency',
	'Trust',
	'Values',
	'Wealth',
	'Wonder'
];

export const TOTAL_PHASE_1_QUESTIONS = 10;
export const TOTAL_PHASE_2_QUESTIONS = 13; // Target number for Phase 2
export const TOTAL_QUESTIONS = TOTAL_PHASE_1_QUESTIONS + TOTAL_PHASE_2_QUESTIONS;
